main = ".open-next/worker.js"
name = "website-v1"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
